#!/bin/bash
#

jq '.user_items | to_entries[] | (.value.number,.value.name,.value.desc)' user.json \
   | paste - - - \
   | grep Mastery \
   | cut -d\" -f2,4 \
   | tr \" "\t" \
   | sed $'s/\t/ | /' \
   | sed 's/ $//'

