#!/bin/bash
#
#

for i in `cat ids-with-cm`
do

  ## 15001-3

  unit=${i%%-*}
  cm=${i#*-}

  unit=`egrep ^$unit cards-w-id-and-rarity | head -1`

  ## 10003 2 Toad Licking

  secondtwo=${unit#* *}
  name=${secondtwo#* *}

  echo "$cm | $name"
done \
	 | sort -t'|' -k2 | sort -k1,1 -r -s
