#!/bin/bash

join -t '|' -o 1.1,1.2,2.1 -a 1 -1 2 -2 2 \
   <(sort -t'|' -k2 Combos/ComboMasteryLevels) \
   <(cat Combos/ComboMasteryTokens |sed 's/\t/ |/' | sort -t'|' -k2) \
   | sed 's/ | /|/' \
   | sort -r -t'|' -k2 \
   | sort -r \
   | sed 's/|/ | /g' \
   | sed 's/ | $//' \
   | sed 's/ $//'

   #<(sort -t'|' -k2 Combos/ComboMasteryTokens) 
