#!/bin/bash
#
#

join -t '|' -o 1.1,1.2,2.1 -a 1 -1 2 -2 2 \
   <(sort -t'|' -k2 Combos/ComboMasteryLevels) \
   <(cat Combos/ComboMasteryTokens | sed $'s/\t/ |/' | sort -t'|' -k2) \
   | sed 's/ | /|/' \
   | sort -t'|' -k2 \
   | sed 's/|/ | /g' \
   | sed 's/ | $//' \
   | sed 's/ $//' \
   | sort -r -s -k1,1

join -t '|' -o 2.2,2.1 -v 2 -1 2 -2 2 \
   <(sort -t'|' -k2 Combos/ComboMasteryLevels) \
   <(cat Combos/ComboMasteryTokens | sed $'s/\t/ |/' | sort -t'|' -k2) \
   | sed 's/|/ | /' \
   | sed 's/ $//' \
   | sort -t'|' -k2 -nr \
   | sed 's/^/0 |/' \
   | grep -v 'Mastery Token'

grep --colour=never 'Mastery Token' Combos/ComboMasteryTokens
