#!/bin/bash
#
#
## create this format
# 150067 4 Mission Doctor
# 150068 3 Mind Switcher Amy


t=cards-w-id-and-rarity

user_id=`grep user_id ~/.at_creds | cut -d= -f2`
password_hash=`grep password_hash ~/.at_creds | cut -d= -f2`

curl -s 'https://cb-live.synapse-games.com/api.php?message=init&user_id='$user_id --data 'password='$password_hash > /tmp/user.json
echo "retrieved user.json"

cat /tmp/user.json | jq -r '.card_data[] | .id,.rarity,.name' | paste -d " " - - - \
    | cut -d" " -f1,2,3- | sed 's/ $//' | sort | uniq > $t

echo "wrote $t"


