#!/bin/bash
#
#

##
## you need user_id and password hash; put them in a file ~/.at_creds
##
## $ cat ~/.at_creds
## user_id=53234
## password_hash=623452345
##

user_id=`grep user_id ~/.at_creds | cut -d= -f2`
password_hash=`grep password_hash ~/.at_creds | cut -d= -f2`

out=units-w-levels

curl -s 'https://cb-live.synapse-games.com/api.php?message=init&user_id='$user_id --data 'password='$password_hash > /tmp/user.json
echo "retrieved user.json"

cat /tmp/user.json | jq '.user_units[] | {id: .unit_id, level: .level, mastery: .mastery_level}' | paste -d " " - - - - - \
   | awk '{ print $3, $5, $7}' | tr -d \" | sort | sed 's/, /-/g' > $out

echo "wrote $out"
wc -l $out

cat /tmp/user.json | jq '.user_combo_mastery[] | {id: .id, level: .level}' | paste -d " " - - - - \
   | awk '{ print $3, $5 }' | tr -d \" | sort | sed 's/, /-/g' > ids-with-cm
echo "wrote ids-with-cm"
wc -l ids-with-cm
